#!/bin/bash
printf "All examples use 20 processes (-np 20)\n"
printf "\n"----\Examples: Operations on a single column----\n"
mpirun -np 20 ./proj2 sr min D
mpirun -np 20 ./proj2 sr max D
mpirun -np 20 ./proj2 sr avg CO
mpirun -np 20 ./proj2 sr number AS gt 55

printf "\n"----\Example: operation on 2 columns with 'number' argument----\n"
mpirun -np 20 ./proj2 sr number AS gt 55 number I gt 20

printf "\n----Example: operation on 3 columns with 'max', 'min', 'avg'----\n"
mpirun -np 20 ./proj2 sr max D min K avg DC

printf "\n----Example: operation on 4 columns with 'number' 'max', 'min', 'avg'----\n"
mpirun -np 20 ./proj2 sr number DI gt 9 max DE min DC avg CY

#
